window.SKA_LINEAGE = {
  width: 1080,
  height: 1890,
  nodes: [
    {id:"mento-rnb", label:"Mento / R&B", year:1952, x:340, tags:["jamaica"], summary:"Mento、米国R&B、サウンドシステム文化が、のちのSKAを生む土台になった。", article:"./genres/mento-rnb.html"},
    {id:"ska", label:"SKA", year:1961, x:340, tags:["jamaica","ska"], summary:"1960年代初頭のジャマイカで形になったSKA。後世にはOriginal Ska / Jamaican Ska / First-wave Skaとも呼び分けられる。", article:"./genres/ska.html"},
    {id:"rocksteady", label:"Rocksteady", year:1966, x:340, tags:["jamaica","rocksteady"], summary:"SKAよりテンポが落ち、ベースとヴォーカルが前に出た短く濃い時代。", article:"./genres/rocksteady.html"},
    {id:"reggae", label:"Early Reggae", year:1968, x:340, tags:["jamaica","reggae"], summary:"Rocksteadyからリズムが変化し、Reggaeと呼ばれる新しいスタイルが定着していく。", article:"./genres/reggae.html"},
    {id:"roots", label:"Roots Reggae", year:1971, x:135, tags:["jamaica","roots"], summary:"Rastafari、社会、政治、アフリカ意識を強く打ち出した70年代の大きな流れ。", article:"./genres/roots-reggae.html"},
    {id:"dub", label:"Dub", year:1972, x:515, tags:["jamaica","dub"], summary:"ミキサー、エコー、リバーブを使い、録音そのものを再構成する音楽。スタジオが楽器になった。", article:"./genres/dub.html"},
    {id:"lovers-rock", label:"Lovers Rock", year:1975, x:970, tags:["uk","reggae","world"], summary:"英国のカリブ系コミュニティーでReggaeとSoulが交わり育った歌の流れ。ジャマイカ本流の外に浮く枝ではなく、移民の暮らしと英国の録音現場から生まれた別の発展として聴く。", article:"./genres/lovers-rock.html"},
    {id:"australian-reggae", label:"Australia / Reggae", year:1978, x:970, tags:["world","reggae"], summary:"ジャマイカのリズムをオーストラリアの多文化的な現場が受け取り、ルーツ、ロック、ダブの感触を混ぜてきた地域の流れ。単一のジャンル名ではなく、土地ごとの実践として見る。", article:"./articles/global-reggae.html"},
    {id:"aotearoa-reggae", label:"Aotearoa / Reggae", year:1980, x:970, tags:["world","reggae"], summary:"アオテアロアでは、レゲエがマオリや太平洋地域の声、ジャズやソウルと結びつき、バンド中心の独自の揺れを育てた。ウェリントンなどの現場から世界へ広がった。", article:"./articles/global-reggae.html"},
    {id:"brazil-reggae", label:"Brazil / Reggae", year:1982, x:970, tags:["world","reggae"], summary:"ブラジルではレゲエが地域のダンス文化やポルトガル語の歌と結びつき、北東部を中心に土着化した。輸入音楽のコピーではなく、土地のリズムで鳴らし直した例。", article:"./articles/global-reggae.html"},
    {id:"japan-ska-dub", label:"Japan / Ska + Dub", year:1980, x:600, tags:["world","japan"], summary:"日本のSKAとDubは一つのジャンル名ではなく、バンド、スタジオ、DJの現場がそれぞれの方法でジャマイカの音を受け取った地域のシーン。", article:"./genres/japan-ska.html"},
    {id:"dancehall", label:"Dancehall", year:1978, x:340, tags:["jamaica","dancehall"], summary:"サウンドシステムとダンスの現場を軸に、Deejayの存在感がさらに強くなった時代。", article:"./genres/dancehall.html"},

    {id:"two-tone", label:"2 Tone", year:1979, x:765, tags:["uk","ska"], summary:"英国でSKA / RocksteadyとPunk / New Waveが接続。Second Waveとも呼ばれる大きなSKAリバイバル。", article:"./genres/two-tone.html"},
    {id:"neo-ska", label:"Neo Ska / Ska Revival", year:1983, x:765, tags:["ska"], summary:"2 Tone以後、各国で広がったSKAリバイバル。日本では『ネオスカ』が2 Tone以降を広めに指す場合もある。", article:"./genres/neo-ska.html"},
    {id:"third-wave", label:"Third Wave Ska", year:1991, x:765, tags:["usa","ska"], summary:"80年代末〜90年代に世界へ広がった第三波。ひとつの音色ではなく、Ska Punkからオーセンティック寄りまでを含む大きな傘。", article:"./genres/third-wave.html"},
    {id:"modern-ska", label:"Modern Ska / New Tone", year:2020, x:765, tags:["ska","modern"], summary:"Third Wave以後もSKAは地下シーンで続き、2010年代末以降は『New Tone』や『第四波』という呼び方も現れた。", article:"./genres/modern-ska.html"},

    {id:"traditional-revival", label:"Trad / Authentic Revival", year:1993, x:610, tags:["ska"], detail:true, summary:"60年代ジャマイカのSKAやRocksteadyの感触を強く受け継ぐリバイバル系。", article:"./genres/traditional-ska-revival.html"},
    {id:"ska-punk", label:"Ska Punk", year:1987, x:680, tags:["ska"], detail:true, summary:"SKAのオフビートとPunk / Hardcoreの速度や歪みを組み合わせた流れ。Third Waveの大きな一角になった。", article:"./genres/ska-punk.html"},
    {id:"ska-core", label:"Ska-core", year:1993, x:870, tags:["ska"], detail:true, summary:"Ska Punkの中でもHardcore色が強い呼び方。The Mighty Mighty Bosstones周辺で広く知られた。", article:"./genres/ska-core.html"},
    {id:"ska-jazz", label:"Ska Jazz", year:1994, x:1010, tags:["ska"], detail:true, summary:"SKAのリズムとJazzの即興、ホーンアレンジを前面に出す流れ。", article:"./genres/ska-jazz.html"},
    {id:"latin-ska", label:"Latin Ska", year:1988, x:870, tags:["ska"], detail:true, summary:"中南米でSKAがRock en Españolや地域のリズムと結びつき、独自の大きなシーンへ発展した。", article:"./genres/latin-ska.html"},

    {id:"digital", label:"Digital Dancehall", year:1985, x:340, tags:["jamaica","dancehall","digital"], summary:"Sleng Tengを象徴に、打ち込み主体のRiddimが主流化。制作方法そのものが変わった。", article:"./genres/digital-dancehall.html"},
    {id:"ragga", label:"Ragga", year:1988, x:340, tags:["jamaica","dancehall","ragga"], summary:"デジタル化したDancehallがさらに硬質化。DeejayやSingjayのスタイルも大きく広がった。", article:"./genres/ragga.html"},
    {id:"reggae-fusion", label:"Reggae Fusion", year:2000, x:515, tags:["jamaica","dancehall"], summary:"Dancehallを軸にHip-Hop、R&B、Popとの融合が進み、世界的なヒットへつながった。", article:"./genres/reggae-fusion.html"},
    {id:"reggae-revival", label:"Reggae Revival", year:2011, x:135, tags:["jamaica","roots","modern"], summary:"Roots Reggaeの思想やバンドサウンドを、若い世代が現代の感覚で再接続した流れ。", article:"./genres/reggae-revival.html"},
    {id:"trap-dancehall", label:"Trap Dancehall", year:2016, x:340, tags:["jamaica","dancehall","modern"], summary:"Trapの808やハイハット、暗い音像を取り込んだ現代Dancehallの大きな流れ。", article:"./genres/trap-dancehall.html"},
    {id:"modern", label:"Jamaica Now", year:2024, x:340, tags:["jamaica","dancehall","modern"], summary:"Dancehall、Trap Dancehall、現代Roots、Pop、Hip-Hop、Afrobeatsとの往来が同時進行している。", article:"./genres/jamaica-now.html"}
  ],
  edges: [
    {from:"mento-rnb",to:"ska",type:"main"},
    {from:"ska",to:"rocksteady",type:"main"},
    {from:"rocksteady",to:"reggae",type:"main"},
    {from:"reggae",to:"dancehall",type:"main"},
    {from:"dancehall",to:"digital",type:"main"},
    {from:"digital",to:"ragga",type:"main"},
    {from:"ragga",to:"trap-dancehall",type:"main"},
    {from:"trap-dancehall",to:"modern",type:"main"},

    {from:"reggae",to:"roots",type:"branch"},
    {from:"roots",to:"reggae-revival",type:"branch"},
    {from:"reggae-revival",to:"modern",type:"branch"},
    {from:"reggae",to:"dub",type:"branch"},
    {from:"reggae",to:"lovers-rock",type:"branch"},
    {from:"reggae",to:"australian-reggae",type:"branch"},
    {from:"reggae",to:"aotearoa-reggae",type:"branch"},
    {from:"reggae",to:"brazil-reggae",type:"branch"},
    {from:"dancehall",to:"reggae-fusion",type:"branch"},
    {from:"reggae-fusion",to:"modern",type:"branch"},

    {from:"ska",to:"two-tone",type:"ska"},
    {from:"ska",to:"japan-ska-dub",type:"ska"},
    {from:"two-tone",to:"neo-ska",type:"ska"},
    {from:"neo-ska",to:"third-wave",type:"ska"},
    {from:"third-wave",to:"modern-ska",type:"ska"},

    {from:"two-tone",to:"ska-punk",type:"ska",detail:true},
    {from:"ska-punk",to:"third-wave",type:"ska",detail:true},
    {from:"third-wave",to:"traditional-revival",type:"ska",detail:true},
    {from:"third-wave",to:"ska-core",type:"ska",detail:true},
    {from:"third-wave",to:"ska-jazz",type:"ska",detail:true},
    {from:"neo-ska",to:"latin-ska",type:"ska",detail:true},
    {from:"traditional-revival",to:"modern-ska",type:"ska",detail:true},
    {from:"ska-punk",to:"modern-ska",type:"ska",detail:true}
  ]
};
