window.SKA_TIMELINE = [
  {year:1950, region:"jamaica", tags:["jamaica","society"], title:"Mento / Jamaican R&B / Sound System", text:"ジャマイカの土着音楽Mento、米国R&Bの影響、そして街のサウンドシステム文化。SKAが生まれる前の土台がそろっていく。"},
  {year:1960, region:"jamaica", tags:["jamaica","ska"], title:"SKA", text:"オフビートを強く刻む、速く跳ねるジャマイカ独自の新しい音楽が形になる。独立前後の空気と重なって一気に広がる。"},
  {year:1964, region:"jamaica", tags:["jamaica","ska"], title:"The Skatalites", text:"SKA初期を代表するミュージシャン集団。Don Drummond、Tommy McCook、Roland Alphonsoらが参加し、初期SKAの演奏と録音を支えた。"},
  {year:1966, region:"jamaica", tags:["jamaica","rocksteady"], title:"Rocksteady", text:"SKAよりテンポを落とし、ベースとヴォーカルが前へ。短い時代ながら、その後のReggaeへ直結する重要な転換点。"},
  {year:1968, region:"jamaica", tags:["jamaica","reggae"], title:"Early Reggae", text:"Rocksteadyからさらにリズムが変化し、Reggaeと呼ばれる新しいスタイルが台頭。"},
  {year:1968, region:"uk", tags:["uk","reggae"], title:"Trojan Records 設立", text:"英国でTrojan Recordsが始動。ジャマイカのSka、Rocksteady、Early Reggaeのレコードを広く流通させ、後の2 Tone世代が音源に出会う土壌を作った。"},
  {year:1971, region:"jamaica", tags:["jamaica","roots"], title:"Roots Reggae", text:"Rastafari、社会や政治、アフリカ意識を強く打ち出すRoots Reggaeが70年代の大きな流れになる。"},
  {year:1972, region:"jamaica", tags:["jamaica","dub"], title:"Dub", text:"ヴォーカルを抜き、ベースとドラムを残し、エコーやリバーブ、ミキサー操作そのものを音楽にする。スタジオが楽器になる。"},
  {year:1978, region:"jamaica", tags:["jamaica","dancehall"], title:"Dancehall", text:"Roots中心の時代から、サウンドシステムとダンスの現場を軸にしたDancehallの時代へ。Deejayの存在感もさらに強くなる。"},
  {year:1979, region:"uk", tags:["uk","ska"], title:"2 Tone", text:"英国でSKA / RocksteadyとPunk / New Waveが接続。The Specials、The Selecter、Madness、The Beatらが新しい世代のSKAを鳴らす。"},
  {year:1985, region:"jamaica", tags:["jamaica","dancehall","digital"], title:"Digital Dancehall / Sleng Teng", text:"Wayne Smith『Under Mi Sleng Teng』の大ヒットを象徴に、打ち込み主体のデジタルRiddimが一気に主流化。制作のルールそのものが変わる。"},
  {year:1988, region:"jamaica", tags:["jamaica","dancehall","ragga"], title:"Ragga / Raggamuffin", text:"デジタル化したDancehallがさらに硬質化。Deejay、Singjay、デジタルRiddimを中心にしたRaggaの時代へ。"},
  {year:1990, region:"usa", tags:["usa","ska"], title:"Third Wave Ska / Ska Punk", text:"米国を中心にSKAとPunkが大きく接続。90年代にThird Waveとして世界的に広がる。"},
  {year:1993, region:"jamaica", tags:["jamaica","dancehall"], title:"Dancehallが世界のPopへ", text:"Shabba Ranks、Beenie Man、Buju Banton、Shaggyらの時代。Dancehallがジャマイカの現場を越えて国際的なPopシーンへ食い込んでいく。"},
  {year:2000, region:"jamaica", tags:["jamaica","dancehall"], title:"Modern Dancehall / Reggae Fusion", text:"DancehallのRiddim文化を保ちながら、Hip-Hop、R&B、Popとの融合がさらに進む。Sean Paulらの世界的成功もこの流れの中にある。"},
  {year:2011, region:"jamaica", tags:["jamaica","roots","modern"], title:"Reggae Revival", text:"Protoje、Chronixx、Kabaka Pyramid、Jah9、Jesse Royalら若い世代が、Roots Reggaeの思想とバンドサウンドを現代の感覚で再接続。"},
  {year:2016, region:"jamaica", tags:["jamaica","dancehall","modern"], title:"Trap Dancehall", text:"Trapの808、ハイハット、暗い音像を取り込んだ新しいDancehallが拡大。Montego Bay周辺のシーンや若い世代から広がる。"},
  {year:2020, region:"jamaica", tags:["jamaica","dancehall","modern"], title:"現代ジャマイカ音楽：ひとつの後継ジャンルではない", text:"Trap Dancehall、Dancehall Pop、現代Roots / Reggae Revival、AfrobeatsやHip-Hopとの往来が同時進行。SKAから始まった変化の速さは今も続いている。"},
  {year:1980, region:"japan", tags:["japan","dub"], title:"日本でもSKA / Reggae / Dubが独自に根付く", text:"輸入盤、クラブ、ライブ、バンド文化を通じて、日本でもSKAやReggae、Dubが独自のシーンを形成していく。"}
];